my_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 10.0.2.2 # Thay đổi ip của postgres cho minikube dùng
      user: postgres
      password: khanh181106
      port: 5432
      dbname: postgres
      schema: sor
      threads: 1
